### ISSUE TITLE
gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by fro0m** [akontsevich/openssl-android-build#1]
./generate-headers.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--   100  4182  100  4182    0     0  14470      0 --:--:-- --:--:-- --:--:-- 14470

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by akontsevich** [comment]
@fro0m , read **README.md**:
# 1. Setup the project
```
$ git clone https://github.com/akontsevich/openssl-android-build.git
$ export OPENSSL_VERSION="openssl-1.0.2o"
```
