### ISSUE TITLE
Qt 5.13 / openssl 1.1

### ISSUE THREAD

**Issue by sipiyou** [akontsevich/openssl-android-build#4]
Hi,

Qt 5.13 has moved to openssl 1.1.1c. While trying to compile openssl 1.1 this script fails.
I think it's only a small fix to do as openssl 1.1 seems to have renamed some options but I am not really sure what to choose.

Could you please update this really great script to support openssl 1.1 ?

Thanks!

**Comment by ekke** [comment]
perhaps try this:  https://github.com/KDAB/android_openssl

**Comment by sipiyou** [comment]
You made my day!!!!! Million thanks!
